<a href="https://colab.research.google.com/github/YefridC09/ST-554_Big_data_analysis/blob/main/HW6_Yefrid_Cordoba/HW6_Yefrid_Cordoba.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework # 6 - ST - 554 Big data analysis

## Author: Yefrid Cordoba

## Part I

### 1

First, we need to connect to the database and import the modules we will use.

In [1]:

#Import the modules
import sqlite3
import pandas as pd

#Connectin to the .sqlite file
MLB = sqlite3.connect("lahman_1871-2022.sqlite")

I will create a function for query execution.

In [2]:
def execute_query(connection, query):
    cursor = connection.cursor()
    try:
        cursor.execute(query)
        print("Query executed successfully")
        #connection.commit()
    except sqlite3.Error as e:
        print(f"The error '{e}' occurred")
    cursor.close()

Now we look for the schema of the database using the function `read_sql()` from `pandas` module.

In [5]:
get_schema = '''
        SELECT *
        FROM sqlite_schema
        WHERE type = "table";
        '''

# creating a dataframe with the schema
schema_MLB = pd.read_sql(get_schema, MLB)
schema_MLB

,type,name,tbl_name,rootpage,sql
0,table,AllstarFull,AllstarFull,2,"CREATE TABLE AllstarFull (\nplayerID TEXT,\nye..."
1,table,Appearances,Appearances,3,"CREATE TABLE Appearances (\nyearID INTEGER,\nt..."
2,table,AwardsManagers,AwardsManagers,4,"CREATE TABLE AwardsManagers (\nplayerID TEXT,\..."
3,table,AwardsPlayers,AwardsPlayers,5,"CREATE TABLE AwardsPlayers (\nplayerID TEXT,\n..."
4,table,AwardsShareManagers,AwardsShareManagers,6,CREATE TABLE AwardsShareManagers (\nawardID TE...
5,table,AwardsSharePlayers,AwardsSharePlayers,7,CREATE TABLE AwardsSharePlayers (\nawardID TEX...
6,table,Batting,Batting,8,"CREATE TABLE Batting (\nplayerID TEXT,\nyearID..."
7,table,BattingPost,BattingPost,9,"CREATE TABLE BattingPost (\nyearID INTEGER,\nr..."
8,table,CollegePlaying,CollegePlaying,10,"CREATE TABLE CollegePlaying (\nplayerID TEXT,\..."
9,table,Fielding,Fielding,11,"CREATE TABLE Fielding (\nplayerID TEXT,\nyearI..."
10,table,FieldingOF,FieldingOF,12,"CREATE TABLE FieldingOF (\nplayerID TEXT,\nyea..."
11,table,FieldingOFsplit,FieldingOFsplit,13,"CREATE TABLE FieldingOFsplit (\nplayerID TEXT,..."
12,table,FieldingPost,FieldingPost,14,"CREATE TABLE FieldingPost (\nplayerID TEXT,\ny..."
13,table,HallOfFame,HallOfFame,15,"CREATE TABLE HallOfFame (\nplayerID TEXT,\nyea..."
14,table,HomeGames,HomeGames,16,"CREATE TABLE HomeGames (\nyearkey INTEGER,\nle..."
15,table,Managers,Managers,17,"CREATE TABLE Managers (\nplayerID TEXT,\nyearI..."
16,table,ManagersHalf,ManagersHalf,18,"CREATE TABLE ManagersHalf (\nplayerID TEXT,\ny..."
17,table,Parks,Parks,19,"CREATE TABLE Parks (\nID INTEGER,\nparkalias T..."
18,table,People,People,21,"CREATE TABLE People (\nID INTEGER,\nplayerID T..."
19,table,Pitching,Pitching,23,"CREATE TABLE Pitching (\nplayerID TEXT,\nyearI..."
20,table,PitchingPost,PitchingPost,24,"CREATE TABLE PitchingPost (\nplayerID TEXT,\ny..."
21,table,Salaries,Salaries,25,"CREATE TABLE Salaries (\nyearID INTEGER,\nteam..."
22,table,Schools,Schools,26,"CREATE TABLE Schools (\nschoolID TEXT,\nname_f..."
23,table,SeriesPost,SeriesPost,27,"CREATE TABLE SeriesPost (\nyearID INTEGER,\nro..."
24,table,Teams,Teams,28,"CREATE TABLE Teams (\nyearID INTEGER,\nlgID TE..."
25,table,TeamsFranchises,TeamsFranchises,29,"CREATE TABLE TeamsFranchises (\nfranchID TEXT,..."
26,table,TeamsHalf,TeamsHalf,30,"CREATE TABLE TeamsHalf (\nyearID INTEGER,\nlgI..."

Now that we know which tables are in the database, we can start working with the data.

### 2

It is necessary to create a query that will do an inner join between the `HallOfFame` table and the `Pitching` table in the `playerID` variable, and return the `GS, G, W, L, IPOuts, CG, SHO` and `SV` columns.

In [12]:
# Creating a query
Pit_HOF = """
    SELECT HallOfFame.playerID, GS, G, W, L, IPOuts, CG, SHO, SV
    From HallOfFame
    Inner JOIN Pitching ON HallOfFame.playerID = Pitching.playerID

    """
P_data = pd.read_sql(Pit_HOF, MLB)
P_data

        playerID  GS   G   W   L  IPouts  CG  SHO  SV
0      abbotji01  29  29  12  12     544   4    2   0
1      abbotji01  33  33  10  14     635   4    1   0
2      abbotji01  34  34  18  11     729   5    1   0
3      abbotji01  29  29   7  15     633   7    0   0
4      abbotji01  32  32  11  14     642   4    1   0
...          ...  ..  ..  ..  ..     ...  ..  ...  ..
23914   zitoba01  33  34   9  14     598   1    0   0
23915   zitoba01   9  13   3   4     161   0    0   0
23916   zitoba01  32  32  15   8     553   1    1   0
23917   zitoba01  25  30   5  11     400   0    0   0
23918   zitoba01   2   3   0   0      21   0    0   0

[23919 rows x 9 columns]

Now we can perform our sum for each of the variables based on the name of the player.

In [13]:
#We perform the sum for each player
Sum_pit = P_data.groupby('playerID').sum()
Sum_pit

             GS     G     W     L  IPouts    CG  SHO   SV
playerID
abbotji01   254   263    87   108    5022    31    6    0
adamsba01  5325  7230  2910  2100  134790  3090  660  225
aguilri01    89   732    86    81    3874    10    0  318
akerja01      0   495    47    45    2238     0    0  123
alexado01   464   561   194   174   10103    98   18    3
...         ...   ...   ...   ...     ...   ...  ...  ...
zachrpa01   154   293    69    67    3532    29    7    3
zahnge01    270   304   111   109    5547    79   20    1
zambrca01   302   354   132    91    5877    10    5    0
zeileto01     0     2     0     0       6     0    0    0
zitoba01    421   433   165   143    7730    12    5    0

[527 rows x 8 columns]

### 3

It is necessary to create a table that matches the `HallOfFame` players with the `Batting` table and shows the values for `AB, R, H, HR, RBI, BB`, and `SO`.

In [15]:
#Creating the query
Bat_HOF = """
    SELECT HallOfFame.playerID, AB, R, H, HR, RBI, BB, SO
    From HallOfFame
    Inner JOIN Batting ON HallOfFame.playerID = Batting.playerID
    """
B_data = pd.read_sql(Bat_HOF, MLB)
B_data

        playerID   AB    R    H  HR    RBI  BB    SO
0      aaronha01  468   58  131  13   69.0  28  39.0
1      aaronha01  602  105  189  27  106.0  49  61.0
2      aaronha01  609  106  200  26   92.0  37  54.0
3      aaronha01  615  118  198  44  132.0  57  58.0
4      aaronha01  601  109  196  30   95.0  59  49.0
...          ...  ...  ...  ...  ..    ...  ..   ...
70765   zitoba01   51    1    6   0    2.0   1  17.0
70766   zitoba01   13    0    0   0    0.0   1   5.0
70767   zitoba01   53    3    4   0    2.0   6  12.0
70768   zitoba01   34    3    5   0    2.0   0   8.0
70769   zitoba01    0    0    0   0    0.0   0   0.0

[70770 rows x 8 columns]

Now we compute the sum of the values by `playerID`.

In [18]:
Sum_bat = B_data.groupby('playerID').sum()
Sum_bat

              AB     R     H   HR     RBI    BB      SO
playerID
aaronha01  12364  2174  3771  755  2297.0  1402  1383.0
abbotji01     21     0     2    0     3.0     0    10.0
abreubo01  25440  4359  7410  864  4089.0  4428  5520.0
adamsba01  15285  1185  3240   45  1125.0   795  2910.0
adamsbo03   4019   591  1082   37   303.0   414   447.0
...          ...   ...   ...  ...     ...   ...     ...
zambrca01    693    75   165   24    71.0    10   240.0
zeileto01   7573   986  2004  253  1110.0   945  1279.0
zimmech01   4546   617  1225   26   625.0   390   511.0
ziskri01    5144   681  1477  207   792.0   533   910.0
zitoba01     344    12    35    0    11.0    18    99.0

[1275 rows x 7 columns]

### 4

Now we are going to join the two tables by pitcher(`playerID`), using the `pd.merge` function.

In [19]:
pit_join = pd.merge(Sum_pit, Sum_bat, on='playerID', how = 'inner')
pit_join

,GS,G,W,L,IPouts,CG,SHO,SV,AB,R,H,HR,RBI,BB,SO
playerID,,,,,,,,,,,,,,,
abbotji01,254,263,87,108,5022,31,6,0,21,0,2,0,3.0,0,10.0
adamsba01,5325,7230,2910,2100,134790,3090,660,225,15285,1185,3240,45,1125.0,795,2910.0
aguilri01,89,732,86,81,3874,10,0,318,139,12,28,3,11.0,6,37.0
akerja01,0,495,47,45,2238,0,0,123,92,3,7,0,4.0,1,51.0
alexado01,464,561,194,174,10103,98,18,3,265,19,44,0,17.0,9,77.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zachrpa01,154,293,69,67,3532,29,7,3,318,9,36,0,6.0,14,128.0
zahnge01,270,304,111,109,5547,79,20,1,43,3,6,0,1.0,0,9.0
zambrca01,302,354,132,91,5877,10,5,0,693,75,165,24,71.0,10,240.0
zeileto01,0,2,0,0,6,0,0,0,7573,986,2004,253,1110.0,945,1279.0
zitoba01,421,433,165,143,7730,12,5,0,344,12,35,0,11.0,18,99.0

## Part II

### 5