<a href="https://colab.research.google.com/github/YefridC09/ST-554_Big_data_analysis/blob/main/HW5_Yefrid__Cordoba.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 5

Author: Yefrid Cordoba

## Part I - Concepts

### 1

In the manufacturing of paper, there are sensors across the paper machine that register data over time, having a big **Volume** of data that continuously is streamed (**Velocity**), this data can be of different types like temperature, flows, pressures, refining energy, basis weight, moisture, strength, speed, etc (**Variety**). As there is always variability in phenomena that cannot be controlled during the process (Heterogeneity of the fibers, equipment malfunction, etc.), the uncertainty needs to be considered in this type of data(**Veracity**). Analyzing data from paper machine operations can be used to predict important product parameters, such as paper strength or productivity, which will help us avoid downtime and product rejections due to quality compliance (**Value**).

### 2

First it is necessary to load the module `sqlite3` and make the connection to the .sqlite file (the file needs to be uploaded to the main folder)

In [72]:
#Import the modules
import sqlite3
import pandas as pd

#Connectin to the .sqlite file
MLB = sqlite3.connect("lahman_1871-2022.sqlite")

I will create a helper function for the querys execution.

In [73]:
def execute_query(connection, query):
    cursor = connection.cursor()
    try:
        cursor.execute(query)
        print("Query executed successfully")
        #connection.commit()
    except sqlite3.Error as e:
        print(f"The error '{e}' occurred")
    cursor.close()

For the creation of a new table, first it is necessary to create a cursor, generate the SQL, execute the SQL code, and finally close the cursor.

In [74]:
#Write the SQL to create a new table that contains the points for each game for both of the team
nt = """
    CREATE TABLE IF NOT EXISTS recent_final (
        LA_dodgers INT,
        T_BlueJays INT);
"""
#execute the SQL code
execute_query(MLB,nt)

Query executed successfully

Checking if the code worked

In [75]:
pd.read_sql('''
        SELECT *
        FROM recent_final;
        ''', MLB)

Empty DataFrame
Columns: [LA_dodgers, T_BlueJays]
Index: []

Now it is necessary to create a query that will add the rows to the table, the code is executed, and the table is shown.

In [76]:
#Create the query to insert the data
c_rows = """
        INSERT INTO recent_final (LA_dodgers, T_BlueJays)
        VALUES
            (4, 11),
            (5, 1),
            (6, 5),
            (2, 6),
            (1, 6),
            (3, 1)
"""

#Executing the query
execute_query(MLB, c_rows)

#Showing the table
pd.read_sql('''
        SELECT *
        FROM recent_final;
        ''', MLB)

Query executed successfully

   LA_dodgers  T_BlueJays
0           4          11
1           5           1
2           6           5
3           2           6
4           1           6
5           3           1

In [77]:
create_row = """
       INSERT INTO
           recent_final (LA_dodgers)
       VALUES
           (5);
"""

execute_query(MLB, create_row)

Query executed successfully

In [78]:
#Showing the table
pd.read_sql('''
        SELECT *
        FROM recent_final;
        ''', MLB)

   LA_dodgers  T_BlueJays
0           4        11.0
1           5         1.0
2           6         5.0
3           2         6.0
4           1         6.0
5           3         1.0
6           5         NaN

Now we update the data with the missing value

In [79]:
mod_row = """
    UPDATE recent_final
    SET T_BlueJays = 4
    WHERE (T_BlueJays is null);
"""

execute_query(MLB, mod_row)

#Showing the table
pd.read_sql('''
        SELECT *
        FROM recent_final;
        ''', MLB)

Query executed successfully

   LA_dodgers  T_BlueJays
0           4          11
1           5           1
2           6           5
3           2           6
4           1           6
5           3           1
6           5           4

Now we delete the rows where the points are greater than 6

In [80]:
del_row = """
    DELETE FROM recent_final
    WHERE LA_dodgers > 6 OR T_BlueJays > 6
    """

execute_query(MLB, del_row)

#Showing the table
pd.read_sql('''
        SELECT *
        FROM recent_final;
        ''', MLB)

Query executed successfully

   LA_dodgers  T_BlueJays
0           5           1
1           6           5
2           2           6
3           1           6
4           3           1
5           5           4

Finally, the created table will be removed from the database

In [81]:
d_table = """
    DROP TABLE recent_final;
"""

execute_query(MLB, d_table)

Query executed successfully

In order to read the data we get the schema

In [82]:
get_schema = '''
        SELECT *
        FROM sqlite_schema
        WHERE type = "table";
        '''

# creating a dataframe with the schema
schema_MLB = pd.read_sql(get_schema, MLB)
schema_MLB

,type,name,tbl_name,rootpage,sql
0,table,AllstarFull,AllstarFull,2,"CREATE TABLE AllstarFull (\nplayerID TEXT,\nye..."
1,table,Appearances,Appearances,3,"CREATE TABLE Appearances (\nyearID INTEGER,\nt..."
2,table,AwardsManagers,AwardsManagers,4,"CREATE TABLE AwardsManagers (\nplayerID TEXT,\..."
3,table,AwardsPlayers,AwardsPlayers,5,"CREATE TABLE AwardsPlayers (\nplayerID TEXT,\n..."
4,table,AwardsShareManagers,AwardsShareManagers,6,CREATE TABLE AwardsShareManagers (\nawardID TE...
5,table,AwardsSharePlayers,AwardsSharePlayers,7,CREATE TABLE AwardsSharePlayers (\nawardID TEX...
6,table,Batting,Batting,8,"CREATE TABLE Batting (\nplayerID TEXT,\nyearID..."
7,table,BattingPost,BattingPost,9,"CREATE TABLE BattingPost (\nyearID INTEGER,\nr..."
8,table,CollegePlaying,CollegePlaying,10,"CREATE TABLE CollegePlaying (\nplayerID TEXT,\..."
9,table,Fielding,Fielding,11,"CREATE TABLE Fielding (\nplayerID TEXT,\nyearI..."
10,table,FieldingOF,FieldingOF,12,"CREATE TABLE FieldingOF (\nplayerID TEXT,\nyea..."
11,table,FieldingOFsplit,FieldingOFsplit,13,"CREATE TABLE FieldingOFsplit (\nplayerID TEXT,..."
12,table,FieldingPost,FieldingPost,14,"CREATE TABLE FieldingPost (\nplayerID TEXT,\ny..."
13,table,HallOfFame,HallOfFame,15,"CREATE TABLE HallOfFame (\nplayerID TEXT,\nyea..."
14,table,HomeGames,HomeGames,16,"CREATE TABLE HomeGames (\nyearkey INTEGER,\nle..."
15,table,Managers,Managers,17,"CREATE TABLE Managers (\nplayerID TEXT,\nyearI..."
16,table,ManagersHalf,ManagersHalf,18,"CREATE TABLE ManagersHalf (\nplayerID TEXT,\ny..."
17,table,Parks,Parks,19,"CREATE TABLE Parks (\nID INTEGER,\nparkalias T..."
18,table,People,People,21,"CREATE TABLE People (\nID INTEGER,\nplayerID T..."
19,table,Pitching,Pitching,23,"CREATE TABLE Pitching (\nplayerID TEXT,\nyearI..."
20,table,PitchingPost,PitchingPost,24,"CREATE TABLE PitchingPost (\nplayerID TEXT,\ny..."
21,table,Salaries,Salaries,25,"CREATE TABLE Salaries (\nyearID INTEGER,\nteam..."
22,table,Schools,Schools,26,"CREATE TABLE Schools (\nschoolID TEXT,\nname_f..."
23,table,SeriesPost,SeriesPost,27,"CREATE TABLE SeriesPost (\nyearID INTEGER,\nro..."
24,table,Teams,Teams,28,"CREATE TABLE Teams (\nyearID INTEGER,\nlgID TE..."
25,table,TeamsFranchises,TeamsFranchises,29,"CREATE TABLE TeamsFranchises (\nfranchID TEXT,..."
26,table,TeamsHalf,TeamsHalf,30,"CREATE TABLE TeamsHalf (\nyearID INTEGER,\nlgI..."

In [83]:
#Reading the data from table AllstarFull
pd.read_sql('SELECT * FROM AllstarFull', MLB)

       playerID  yearID  gameNum        gameID teamID lgID  GP startingPos
0     gomezle01    1933        0  ALS193307060    NYA   AL   1           1
1     ferreri01    1933        0  ALS193307060    BOS   AL   1           2
2     gehrilo01    1933        0  ALS193307060    NYA   AL   1           3
3     gehrich01    1933        0  ALS193307060    DET   AL   1           4
4     dykesji01    1933        0  ALS193307060    CHA   AL   1           5
...         ...     ...      ...           ...    ...  ...  ..         ...
5511  rileyau01    2022        0  NLS202207190    ATL   NL   1        None
5512  schwaky01    2022        0  NLS202207190    PHI   NL   1        None
5513   sotoju01    2022        0  NLS202207190    WAS   NL   1        None
5514  swansda01    2022        0  NLS202207190    ATL   NL   1        None
5515  willide03    2022        0  NLS202207190    MIL   NL   1        None

[5516 rows x 8 columns]